### ISSUE TITLE
[meta] cartocontext refactor (not including cc.map)

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#128]
- [x] `cc.__init__`
    - [x] private methods to reduce the number of branches (if statements) #129
        * cartoframes.credentials checks
        * instantiation stuff like base_url, api_key, etc.
- [x] `cc.write`
    - [x] encode_geom to private method #129
    - [x] table_exists to private method #129
    - [x] allow for batching large dataframes #136 

`cc.map` refactor is in #138

**Comment by andy-esch** [comment]
All finished except for the batch imports, which is on it's way.
