### ISSUE TITLE
Visualization API redesign

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1343]
Related issue https://github.com/CartoDB/cartoframes/issues/1301

## Context

After some observations, we've the need of change **some aspects** of the visualization API with the objective of **unifying** the different components and creating an **agnostic API** that doesn't depend, in API terms, on the third party libraries (mainly, **CARTO VL style syntax**)

This EPIC summarizes the conclusions from the research process we've followed. The main purpose of this task is to **divide** the refactor process in smaller pieces, in order to detail them as much as possible. This will allow us to:

- Have a clear definition of what we want to achieve in each task
- Follow the progress effectively
- Be able to modify or remove what we consider is out of the scope

We've separated this task in **five** big areas. The details of each one are in their respective issue description.

- [x] [ Widgets #1349 ] - Refactor Widgets API
- [x] [ Legends #1347 ] - Refactor Legends API  
- [x] [ Popups #1348 ] - Refactor Popups API
- [x] [ Style #1345 ] - Change Style class API to accept style-properties as parameters
- [x] [ Layer Helpers  #1350 ] - Refactor using the new Layer implementation

**Comment by Jesus89** [comment]
Closing via https://github.com/CartoDB/cartoframes/pull/1399
