### ISSUE TITLE
Creating docker-hub server for launch

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#199]
Set up a docker hub server that will allow people to login and try out CARTOFrames in a notebook environment. 

## Todo
- [ ] Generate a API key for a CARTO account 
- [x] Build notebook image that comes pre-loaded with examples, CARTOFrames and a reference to the APKey
- [ ] Investigate resource tracking etc on the notebook

**Comment by stuartlynn** [comment]
Have created a notebook server at www.cartoframes.com which allows users to login with gihub and comes pre-populated with example notebooks

API Keys for the example CARTO account are setup as environment variables

**Comment by andy-esch** [comment]
This is supplanted by #264
