### ISSUE TITLE
Create HTML templates for different visualizations

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#596]
Related issues:
- https://github.com/CartoDB/cartoframes/issues/574

Context
===

We need to define some default HTML templates that can be used for different use cases. These use cases are listed below, although we could add more to the list:

- Implementation (basic):
    - Interactivity (popup) template. We already have a basic interactivity enabled, but there're different interactivity use cases. For this one, we should have a basic interactivity template as it's being used right now, but it should parse the value correctly depending on the format (color, string, number, image...)
    - ~Widget (basic) - boilerplate for Legends + Widgets~ --> TBD in the Legends Epic
- Implementation (advanced):
    - Animation controls template: Display animation controls, as we do in [this example](https://carto.com/developers/carto-vl/examples/#example-add-animation-controls)
    - Labeling

- ~~Analysis on templates & configuration. It will be nice to have a catalog of 'templates', and then focus on the most common ones.~~ --> Next

This issue is separated in different issues
---

- [x] Error Template: with https://github.com/CartoDB/carto-vl/issues/1309
- [x] Interactivity & popup: https://github.com/CartoDB/cartoframes/issues/641
- [ ] Labels: https://github.com/CartoDB/cartoframes/issues/642
- [x] Animation Controls: https://github.com/CartoDB/cartoframes/issues/643

**Comment by andy-esch** [comment]
We should probably include an Error template in this list too

**Comment by elenatorro** [comment]
I added the Error Template, which is related with ["Improve JavaScript error messaging"](https://github.com/CartoDB/carto-vl/issues/1309) 👍

**Comment by VictorVelarde** [comment]
As discussed together, we're going to give more priority to https://github.com/CartoDB/cartoframes/issues/641 not the rest by now

**Comment by andy-esch** [comment]
@elenatorro, how do you think we're doing on this one? It looks like we might be able to close it?

**Comment by cmongut** [comment]
Pinging @elenatorro 🙂 to decide

**Comment by Jesus89** [comment]
@elenatorro says we can close it :sparkles:
