### ISSUE TITLE
[Docs - EPIC] Documentation Refactor

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#967]
**[EPIC]** Milestone https://github.com/CartoDB/cartoframes/milestone/25

Context: [Internal Document](https://docs.google.com/document/d/16UTXbj2M-s1ZX-g_t99N1ad4J-byfAj1eP6HMYnRuA4/edit)

## Done

✅ Reference

<details>
<summary>Closed issues:</summary>
<ul>
<li>Publish Reference Section  https://github.com/CartoDB/developers/issues/639</li>
<li>Move reference to Dev Center https://github.com/CartoDB/cartoframes/issues/937</li>
<li>Add Reference Sidebar https://github.com/CartoDB/developers/issues/637</li>
<li>Apply Styles https://github.com/CartoDB/developers/issues/638</li>
<li>Support multiversion https://github.com/CartoDB/developers/issues/640</li>
<li>Change CARTOframes version to use the last one and publish</li>
<li>Review docstrings https://github.com/CartoDB/cartoframes/issues/841</li>
<li>Links from guides https://github.com/CartoDB/cartoframes/issues/980</li>
</ul>
</details>

✅ Examples - [**Examples guidelines**](https://docs.google.com/document/d/1-PRMkY4DgQGpHtsqBLFJtdYvFV4o1muP-O5E43O-NL0/edit#)

<details>
<summary>Closed issues:</summary>
<ul>
<li>Embed notebooks in dev center https://github.com/CartoDB/cartoframes/issues/988</li>
<li>Review current examples https://github.com/CartoDB/cartoframes/issues/985</li>
<li>Clean `debug` examples https://github.com/CartoDB/cartoframes/issues/986</li>
<li>Add 'Real use cases' directory https://github.com/CartoDB/cartoframes/issues/987</li>
</ul>
</details>

✅   Guides

<details>
<summary>Closed issues:</summary>
<ul>
<li>Introduction https://github.com/CartoDB/cartoframes/issues/990</li>
<li>Quickstart https://github.com/CartoDB/cartoframes/issues/966</li>
<li>Install CARTOframes in your Notebooks https://github.com/CartoDB/cartoframes/issues/991</li>
<li>Login to CARTO Platform https://github.com/CartoDB/cartoframes/issues/993</li>
</ul>
</details>

## Doing

⚠️  Guides [DOING] - **RC1**

- [ ] 12. Spatial Analysis with PostGIS https://github.com/CartoDB/cartoframes/issues/1160 --> Create example

- ~~[ ] 07. Manage your Data https://github.com/CartoDB/cartoframes/issues/994~~ Canceled
- ~~[ ] 11. Publish and share https://github.com/CartoDB/cartoframes/issues/998~~ Canceled

- [x] 06. Visualize your Data https://github.com/CartoDB/cartoframes/issues/992
- [x] 08. Use Location Data Services https://github.com/CartoDB/cartoframes/issues/995
- [x] 09. Enrich your Datasets https://github.com/CartoDB/cartoframes/issues/997
- [x] 10. Discover Data https://github.com/CartoDB/cartoframes/issues/996

### Guides Workflow

[Internal documentation with useful information for guides](https://github.com/CartoDB/cartoframes/blob/develop/docs/developers/guide-boilerplate.md)

1. Create a branch from `development` with the format `guides/name-of-your-guide`
2. Add the basic structure of your guide. Each guide should contain the following sections:
    * Guide's purpose / summary: what the guides include or what it aims to show to the user
    * Guide's content
    * Guide's conclusion
3. First review: ask for **structure** review
    * Ask in the channel for structure review
4. Once the structure review has passed ✅, write the content. -> **Create a Notebook**
5. Second review: ask for **content** review
    * @andy-esch: data-related content review 
    * @makella: visualization-related content review
    * Any other member of the team can also participate in the content review 
6. Add it to the Guide's [Introduction page](https://github.com/CartoDB/cartoframes/blob/develop/docs/developer-center/guides/01-Introduction.md).

![Screenshot 2019-11-18 at 15 16 34](https://user-images.githubusercontent.com/3824953/69059772-7b280500-0a16-11ea-9a86-fd72c3407552.png)

> **Note:** this means we should add the code in HTML. There should be two guides per row. Ask @elenatorro for review/help with this.

```html
<div class="doc-guides__cartoframes-row">
  <div class="doc-guides__cartoframes-block">
    <span class="doc-guides__title">
      <a href="/developers/cartoframes/guides/Install-CARTOframes-in-your-Notebooks/">Installation</a>
    </span>
    <p class="doc-guides__description">This guide walks you through the process of installing CARTOframes in a Jupyter Notebook</p>
  </div>

  <div class="doc-guides__cartoframes-block">
    <span class="doc-guides__title">
      <a href="/developers/cartoframes/guides/Login-to-CARTO-Platform/">Login into CARTO</a>
    </span>
    <p class="doc-guides__description">Learn how to authenticate against CARTO</p>
  </div>
</div>
```

7. Deploy the branch to the Developer center for **Acceptance**.
    * If you've any question related with the devcenter, ask @elenatorro 
    * Ask in the channel for acceptance review

**Comment by elenatorro** [comment]
We can close this epic cause the refactor is finished 🎉 we'll continue developing docs related issues separately from this epic 🚀
